Change pubsub code
CIT-Autonomous-Robot-Lab/emcl2_ros2 pull request #10
Opened 2023-05-09 15:16 UTC by Kenzo-Fujisaki

パブリッシャとサブスクライバの箇所をROS 2に移行しました。

2023-05-10 00:03 UTC, Kenzo-Fujisaki commented
@uhobeike レビューお願いします。

2023-05-10 00:21 UTC, uhobeike requested changes
一旦ここまでの、修正をお願いします。
終わったらまたレビューの依頼をお願いします。

2023-05-10 00:21 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +
ここの改行いらないです
↓も同じ
publisherとsubscriberの宣言は改行なしでお願いします

2023-05-10 00:21 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +	void cbScan(const sensor_msgs::msg::LaserScan::SharedPtr msg);
型の前にあるconstを取り除いて
::ConstSharedPtrを使うようにしましょう

2023-05-10 00:21 UTC, uhobeike commented on src/emcl2_node.cpp
> +	auto callback = std::bind(&EMcl2Node::cbScan, this, std::placeholders::_1);
ここのcalllbackはそのまま
create_subscriptionの引数にぶち込んでください
なぜここだけ別れてるのでしょうか？？？？？

2023-05-10 02:31 UTC, Kenzo-Fujisaki commented
@uhobeike 修正が完了したのでレビューお願いします。
対策法がなくやむを得ない事態に陥ったので`git push -f`を実行しました。申し訳ありません。

2023-05-10 02:51 UTC, uhobeike commented
良くないですね。`git revert`を使えば修正できたと思います

2023-05-12 02:35 UTC, uhobeike approved these changes
大丈夫そうです。

2023-05-12 02:35 UTC, uhobeike commented
@Kenzo-Fujisaki 一応確認ですが、動作確認はしましたか？

2023-05-12 02:42 UTC, Kenzo-Fujisaki commented
`ros2 topic list`を打ち込んだところ、
```
/alpha
/initialpose
/mcl_pose
/particlecloud
/scan
```
のトピックが確認できました。

2023-05-12 02:44 UTC, uhobeike commented
私も確認しました
```
ros2 run emcl2 emcl2_node
ros2 run rqt_graph rqt_graph
```
![rosgraph_emc2_node](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/assets/40545422/89144bfd-758e-45e2-a86f-df2c31b21493)

2023-05-12 02:46 UTC, uhobeike commented
@Kenzo-Fujisaki マージお願いします！

2023-05-12 02:46 UTC, Kenzo-Fujisaki commented
申し訳ありません。
`ros2 topic list`の前に`ros2 run emcl2 emcl2_node`の実行が抜けていました。

2023-05-12 02:48 UTC, Kenzo-Fujisaki commented
@uhobeike サービスやパラメータ関連の移行はまた他のプルリクを出す形になりますか？

2023-05-12 05:20 UTC, closed without merging