Porting/parameter of ros2 emcl2 node
CIT-Autonomous-Robot-Lab/emcl2_ros2 pull request #13
Opened 2023-05-13 07:31 UTC by ShimonShoji

以下のファイルのパラメータの記述形式をROS 2に移行しました。
・emcl2_node.cpp
・emcl2_node.h

2023-05-13 07:32 UTC, ShimonShoji commented
@uhobeike 
チェックよろしくお願いします。

2023-05-13 07:51 UTC, uhobeike approved these changes
確認お願いします。

2023-05-13 07:51 UTC, uhobeike commented on src/emcl2_node.cpp
> +//   this->declare_parameter("odom_fw_dev_per_fw", 0.19);
なぜコメントアウトのままですか？

2023-05-13 07:51 UTC, uhobeike commented
@ShimonShoji 動作確認の方もお願いします。

2023-05-13 08:14 UTC, ShimonShoji commented on src/emcl2_node.cpp
> +//   this->declare_parameter("odom_fw_dev_per_fw", 0.19);
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/398ea8daf4de0fdc9467ddb0ee2a82eb2c166e07/src/emcl2_node.cpp#L104

からコメントアウトを外したときのエラーの対処に、パラメータの記述形式の移行に収まらない作業が要ると思ったためです。一応取り組んではいました✋ コメントアウト外せるようにしたほうが良いですかね。

2023-05-13 08:14 UTC, ShimonShoji commented
@uhobeike 分かりました。確認ありがとうございます。

2023-05-13 08:22 UTC, uhobeike commented on src/emcl2_node.cpp
> +//   this->declare_parameter("odom_fw_dev_per_fw", 0.19);
たしかに、そうですね。
`OdomModel.cpp`の方の移行はまだ済んでないので
コメントアウトのままで良さそうです。

2023-05-13 08:43 UTC, ShimonShoji commented
動作確認です↓

`ros2 run emcl2 emcl2_node`
`ros2 param list`
と打ったときに以下のパラメータが表示されました。
今回移行してコメントアウトを外した部分のパラメータは全て確認できてそうです。
```
/emcl2_node:
  alpha_threshold
  base_frame_id
  expansion_radius_orientation
  expansion_radius_position
  extraction_rate
  footprint_frame_id
  global_frame_id
  initial_pose_a
  initial_pose_x
  initial_pose_y
  laser_max_range
  laser_min_range
  num_particles
  odom_frame_id
  odom_freq
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  range_threshold
  scan_increment
  sensor_reset
  use_sim_time
```

2023-05-13 09:43 UTC, ShimonShoji commented
すみません、get paramの方の確認作業をちゃんと理解できていないのですが、一応、emcl2.param.yaml内に以下を記述して、

```
emcl2_node:
  ros__parameters:
    global_frame_id: "mappa"
```
ターミナルで以下のコマンドを打ったところ
`ros2 run emcl2 emcl2_node __params:=emcl2.param.yaml`
`ros2 param get emcl2_node global_frame_id`

以下のように出ました。これでダイジョブなんですかね。
`String value is: map`

扱ったパラメータは以下になります。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/398ea8daf4de0fdc9467ddb0ee2a82eb2c166e07/src/emcl2_node.cpp#L43

2023-05-13 09:54 UTC, uhobeike commented
使用するコマンドが古いみたいです。
以下の用に実行してみてください。
```
ros2 run emcl2 emcl2_node --ros-args --params-file param_path
```

> すみません、get paramの方の確認作業をちゃんと理解できていないのですが、一応、emcl2.param.yaml内に以下を記述して、
> 
> ```
> emcl2_node:
>   ros__parameters:
>     global_frame_id: "mappa"
> ```
> 
> ターミナルで以下のコマンドを打ったところ `ros2 run emcl2 emcl2_node __params:=emcl2.param.yaml` `ros2 param get emcl2_node global_frame_id`
> 
> 以下のように出ました。これでダイジョブなんですかね。 `String value is: map`
> 
> 扱ったパラメータは以下になります。
> 
> https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/398ea8daf4de0fdc9467ddb0ee2a82eb2c166e07/src/emcl2_node.cpp#L43

2023-05-13 10:06 UTC, ShimonShoji commented
行けてそうです！
emcl2.param.yaml内に以下を記述して、
```
emcl2_node:
  ros__parameters:
    global_frame_id: "mappa"
```
ターミナルで以下のコマンドを打ったところ
ros2 run emcl2 emcl2_node --ros-args --params-file ./src/emcl2_ros2/config/emcl2.param.yaml
ros2 param get emcl2_node global_frame_id

以下のように出ました。
String value is: mappa

扱ったパラメータは以下になります。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/398ea8daf4de0fdc9467ddb0ee2a82eb2c166e07/src/emcl2_node.cpp#L43

2023-05-13 10:08 UTC, ShimonShoji commented
他のパラメータの確認も必要ですかね...?

2023-05-13 10:08 UTC, uhobeike commented
確認ありがとうございます。
[パラメータファイル](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/porting/parameter-of-ros2-emcl2-node/config/emcl2.param.yaml)にデフォルトのパラメータを追記して
pushしてほしいです。

2023-05-13 11:05 UTC, ShimonShoji commented
emcl2.param.yaml
pushしました！

2023-05-13 11:37 UTC, uhobeike commented
へんなことになってますよー。（変更差分）

2023-05-13 13:12 UTC, ShimonShoji commented
@uhobeike 
OdomModel.cppの移行に際し、該当のコメントアウトを外しました。
確認よろしくおねがいします。

2023-05-13 13:14 UTC, uhobeike commented
動作確認は、しましたか？

2023-05-13 13:14 UTC, ShimonShoji commented
`ros2 run emcl2 emcl2_node`
`ros2 param list`
を打った際に以下のパラメータが表示されました。
```
/emcl2_node:
  alpha_threshold
  base_frame_id
  expansion_radius_orientation
  expansion_radius_position
  extraction_rate
  footprint_frame_id
  global_frame_id
  initial_pose_a
  initial_pose_x
  initial_pose_y
  laser_max_range
  laser_min_range
  num_particles
  odom_frame_id
  odom_freq
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  range_threshold
  scan_increment
  sensor_reset
  use_sim_time
```

2023-05-13 13:24 UTC, ShimonShoji commented
また、
[emcl2.param.yaml](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/porting/parameter-of-ros2-emcl2-node/config/emcl2.param.yaml) 内のパラメータ base_frame_idを
`base_frame_id: "gase_link"`
と設定し、

以下のコマンドを打ったところ、
`ros2 run emcl2 emcl2_node --ros-args --params-file ./src/emcl2_ros2/config/emcl2.param.yaml`
`ros2 param get emcl2_node base_frame_id`

以下のように反映されました
`String value is: gase_link`

2023-05-13 14:33 UTC, uhobeike requested changes
修正＆動作確認お願いします。

2023-05-13 14:33 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> -	// std::shared_ptr<OdomModel> initOdometry(void);
ここのコメントアウトを外さないと
initOdometryが実行されないです（動作確認できてない部分がある）

2023-05-13 14:51 UTC, ShimonShoji commented
あれ、これを見るとコメントアウトを外せている気はします
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/3a0c01038341e8eda26c3788ba9352c7c1048085/include/emcl2/emcl2_node.h#L86

パラメータの表示に、[OdomModelのカッコ内](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/3a0c01038341e8eda26c3788ba9352c7c1048085/src/emcl2_node.cpp#LL105C1-L105C57)のパラメータの確認はできませんでしたね。。

2023-05-13 14:56 UTC, uhobeike requested changes
すみません。
レビューし直しました。
確認お願いします。

2023-05-13 14:56 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> -	// std::shared_ptr<OdomModel> initOdometry(void);
ここではなかった。

2023-05-13 14:56 UTC, uhobeike commented on src/emcl2_node.cpp
>  	// std::shared_ptr<OdomModel> om = std::move(initOdometry());
ここのコメントアウトを外す必要があります。

2023-05-13 14:58 UTC, ShimonShoji commented on src/emcl2_node.cpp
>  	// std::shared_ptr<OdomModel> om = std::move(initOdometry());
あ、了解です！再度確認してみます

2023-05-13 14:58 UTC, uhobeike commented on src/emcl2_node.cpp
>  	// std::shared_ptr<OdomModel> om = std::move(initOdometry());
initOdometry()が呼ばれてないので
こういうことです
> パラメータの表示に、[OdomModelのカッコ内](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/3a0c01038341e8eda26c3788ba9352c7c1048085/src/emcl2_node.cpp#LL105C1-L105C57)のパラメータの確認はできませんでしたね。。

2023-05-13 15:27 UTC, ShimonShoji commented
`ros2 run emcl2 emcl2_node`
`ros2 param list`
を打った際に以下のパラメータが表示されました。
（[OdomModelのカッコ内](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/3a0c01038341e8eda26c3788ba9352c7c1048085/src/emcl2_node.cpp#LL105C1-L105C57)のパラメータも確認できました、ありがとうございます。）

```
/emcl2_node:
  alpha_threshold
  base_frame_id
  expansion_radius_orientation
  expansion_radius_position
  extraction_rate
  footprint_frame_id
  global_frame_id
  initial_pose_a
  initial_pose_x
  initial_pose_y
  laser_max_range
  laser_min_range
  num_particles
  odom_frame_id
  odom_freq
  odom_fw_dev_per_fw
  odom_fw_dev_per_rot
  odom_rot_dev_per_fw
  odom_rot_dev_per_rot
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  range_threshold
  scan_increment
  sensor_reset
  use_sim_time
```

2023-05-14 02:03 UTC, uhobeike requested changes
修正＆動作確認お願いします。

2023-05-14 02:03 UTC, uhobeike commented on config/emcl2.param.yaml
> +    global_frame_id: "map"
細かい話ですが
global_frame_id
odom_frame_id
base_frame_id
footprint_frame_id
という順番にしましょう

2023-05-14 02:03 UTC, uhobeike commented on src/emcl2_node.cpp
> +// 	 this->declare_parameter("laser_likelihood_max_dist", 0.2);
ここらへんどのコメントアウトも外して
確認お願いします。

2023-05-14 02:59 UTC, ShimonShoji commented on config/emcl2.param.yaml
> +    global_frame_id: "map"
emcl2_node.cppの方でも順番を変えたほうが良いでしょうか？
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/3a0c01038341e8eda26c3788ba9352c7c1048085/src/emcl2_node.cpp#L44
@uhobeike

2023-05-14 02:59 UTC, uhobeike commented on config/emcl2.param.yaml
> +    global_frame_id: "map"
それは大丈夫です
確認ありがとうございます

2023-05-14 04:14 UTC, ShimonShoji commented
以下のあたりのコメントアウトを外しました。確認よろしくお願いします。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/bb0cb31bf47b8e7193b4ff7c653fb5056f19c1b9/src/emcl2_node.cpp#L122

2023-05-14 04:16 UTC, ShimonShoji commented
`ros2 run emcl2 emcl2_node`
`ros2 param list`
を打った際に以下のパラメータが表示されました。
（[コメントアウトを外した部分のパラメータ](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/bb0cb31bf47b8e7193b4ff7c653fb5056f19c1b9/src/emcl2_node.cpp#L122)も確認できました。）
```
/emcl2_node:
  alpha_threshold
  base_frame_id
  expansion_radius_orientation
  expansion_radius_position
  extraction_rate
  footprint_frame_id
  global_frame_id
  initial_pose_a
  initial_pose_x
  initial_pose_y
  laser_likelihood_max_dist
  laser_max_range
  laser_min_range
  num_particles
  odom_frame_id
  odom_freq
  odom_fw_dev_per_fw
  odom_fw_dev_per_rot
  odom_rot_dev_per_fw
  odom_rot_dev_per_rot
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  range_threshold
  scan_increment
  sensor_reset
  use_sim_time
```

2023-05-14 04:25 UTC, ShimonShoji commented
また、
[emcl2.param.yaml](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/porting/parameter-of-ros2-emcl2-node/config/emcl2.param.yaml) 内のパラメータlaser_likelihood_max_distを以下のように設定し、
`laser_likelihood_max_dist: 0.4`

以下のコマンドを打ったところ、
`ros2 run emcl2 emcl2_node --ros-args --params-file ./src/emcl2_ros2/config/emcl2.param.yaml`
`ros2 param get emcl2_node laser_likelihood_max_dist`

以下のように反映されました。
`Double value is: 0.4`

2023-05-14 05:24 UTC, uhobeike approved these changes
大丈夫そうです！

2023-05-14 05:24 UTC, uhobeike commented
マージお願いします！

2023-05-14 05:24 UTC, ShimonShoji commented
確認ありがとうございます！了解です

2023-05-14 05:55 UTC, ShimonShoji commented
[emcl2.param.yaml](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/13/commits/9a8f39d7ef0baacf761cb3e82979756837a42f48)を修正してpushしました。
確認よろしくおねがいします。

2023-05-14 05:57 UTC, uhobeike approved these changes
問題なさそうです。

2023-05-14 05:58 UTC, uhobeike commented
@ShimonShoji 
@AtsukiUsui が新しいPRをマージしたので、それをマージで取り込んでから、マージお願いします。

2023-05-14 06:14 UTC, ShimonShoji commented
確認ありがとうございます。
新しいPRを取り込んだので、マージします。

2023-05-14 06:15 UTC, merged