Porting/mcl
CIT-Autonomous-Robot-Lab/emcl2_ros2 pull request #15
Opened 2023-05-13 15:42 UTC by AtsukiUsui

以下のファイルをROS 2に移行しました。

- Mcl.h
- Mcl.cpp

2023-05-13 15:42 UTC, AtsukiUsui commented
@uhobeike 
チェックお願いします。

2023-05-14 01:54 UTC, uhobeike requested changes
確認よろしくお願いします。

2023-05-14 01:54 UTC, uhobeike commented on src/Mcl.cpp
> +double Mcl::cos_[(1 << 16)];
`double Mcl::cos_[(1 << 16)];`の前に改行がほしいです。
他の関数は改行されて分かれてるはずです。
ここだけ改行がないのは違和感です。

2023-05-14 01:54 UTC, uhobeike commented on src/Mcl.cpp
> +// void Mcl::setScan(const sensor_msgs::msg::LaserScan::ConstPtr & msg)
ここら下のコメントアウトはなんですか？

2023-05-14 01:58 UTC, AtsukiUsui commented on src/Mcl.cpp
> +double Mcl::cos_[(1 << 16)];
修正します

2023-05-14 02:05 UTC, AtsukiUsui commented on src/Mcl.cpp
> +// void Mcl::setScan(const sensor_msgs::msg::LaserScan::ConstPtr & msg)
ROS 2移行を行う上で元のコードをコメントアウトしてました。

buildが通ったので削除します。

2023-05-14 02:16 UTC, AtsukiUsui commented
@uhobeike 
指摘していただいた部分の修正を行いました。
チェックお願いします。

2023-05-14 03:27 UTC, uhobeike requested changes
修正お願いします。

2023-05-14 03:27 UTC, uhobeike commented on include/emcl2/Mcl.h
> -	void setScan(const sensor_msgs::LaserScan::ConstPtr &msg);
setScanの引数の型を
以下の型の型に合わせてほしいです。
実装のc++の方も同じくお願いします。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/471632dc9b9aeea26a2534fc1515080d76bedd51/src/emcl2_node.cpp#L115

2023-05-14 03:27 UTC, uhobeike commented on src/Mcl.cpp
> +		RCLCPP_ERROR(rclcpp::get_logger("mcl"), "NO PARTICLE");
nodeの名前は、mclではないですよ。
`emcl2_node`です。
合わせてください。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/471632dc9b9aeea26a2534fc1515080d76bedd51/src/emcl2_node.cpp#L14

2023-05-14 03:27 UTC, uhobeike commented on src/Mcl.cpp
> +void Mcl::setScan(const sensor_msgs::msg::LaserScan::ConstPtr & msg)
同じく

2023-05-14 03:27 UTC, uhobeike commented on src/Mcl.cpp
> +				RCLCPP_ERROR(rclcpp::get_logger("mcl"), "RESAMPLING FAILED");
同じく

2023-05-14 03:50 UTC, AtsukiUsui commented on include/emcl2/Mcl.h
> -	void setScan(const sensor_msgs::LaserScan::ConstPtr &msg);
修正します

2023-05-14 03:57 UTC, AtsukiUsui commented on src/Mcl.cpp
> +void Mcl::setScan(const sensor_msgs::msg::LaserScan::ConstPtr & msg)
修正します

2023-05-14 03:59 UTC, AtsukiUsui commented on src/Mcl.cpp
> +		RCLCPP_ERROR(rclcpp::get_logger("mcl"), "NO PARTICLE");
修正します

2023-05-14 04:02 UTC, AtsukiUsui commented on src/Mcl.cpp
> +				RCLCPP_ERROR(rclcpp::get_logger("mcl"), "RESAMPLING FAILED");
修正します

2023-05-14 04:04 UTC, AtsukiUsui commented
@uhobeike
指摘していただいた部分の修正を行いました。
チェックお願いします。

2023-05-14 05:03 UTC, uhobeike requested changes
修正お願いします。

2023-05-14 05:03 UTC, uhobeike commented on src/Mcl.cpp
> +void Mcl::cbScan(sensor_msgs::msg::LaserScan::ConstSharedPtr msg)
どうして、関数名変わってしまいましたかね？
コピペしたのでしょうか？

2023-05-14 05:03 UTC, uhobeike commented on include/emcl2/Mcl.h
> +	void cbScan(sensor_msgs::msg::LaserScan::ConstSharedPtr msg);
ここも

2023-05-14 05:26 UTC, AtsukiUsui commented
@uhobeike
指摘していただいた部分の修正を行いました。
チェックお願いします。

2023-05-14 05:37 UTC, uhobeike approved these changes
大丈夫そうです。

2023-05-14 05:38 UTC, uhobeike commented
@AtsukiUsui マージお願いします。

2023-05-14 05:38 UTC, merged