Porting service code for ROS 2
CIT-Autonomous-Robot-Lab/emcl2_ros2 pull request #18
Opened 2023-05-14 10:58 UTC by Kenzo-Fujisaki

以下のファイルのサービス箇所をROS 2に移行し、[`ros::service::call`](https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/c95d729f52fd5fd3a0e9ac772862e643e8f06faa/src/emcl2_node.cpp#L137)の箇所をサブスクライバとして実装しました。また`package.xml`に`<depend>std_srvs</depend>`を付け足しました。

- emcl2_node,h
- emcl2_node.cpp

2023-05-14 10:59 UTC, Kenzo-Fujisaki commented
@uhobeike レビューお願いします。

2023-05-14 10:59 UTC, uhobeike commented
@Kenzo-Fujisaki 動作確認もお願いします。実際にサービスをコマンドで呼び出せる関数は呼び出して見てください。

2023-05-14 11:06 UTC, Kenzo-Fujisaki commented
`ros2 run emcl2 emcl2_node `
`ros2 service call /global_localization std_srvs/srv/Empty {}\` を実行したところ
```
requester: making request: std_srvs.srv.Empty_Request()

response:
std_srvs.srv.Empty_Response()
```
`ros2 run emcl2 emcl2_node `
`ros2 topic list` を実行したところ

```
/map
```
が確認できました。

2023-05-14 11:17 UTC, uhobeike requested changes
修正よろしくお願いします。

2023-05-14 11:17 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +	void receiveMap(nav_msgs::msg::OccupancyGrid::SharedPtr msg);
ConstSharedPtrを使用してください。
受け取ったメッセージというのは、変更しないので
Constをつけて明示的にしたほうが良いです。

2023-05-14 11:17 UTC, uhobeike commented on src/emcl2_node.cpp
> +void EMcl2Node::receiveMap(nav_msgs::msg::OccupancyGrid::SharedPtr msg)
同じく

2023-05-14 11:17 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +	  std::shared_ptr<std_srvs::srv::Empty::Request> req,
std_srvs::srv::Empty::Request::SharedPtrの型を使用しましょう

2023-05-14 11:17 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +	  std::shared_ptr<std_srvs::srv::Empty::Response> res);
std_srvs::srv::Empty::Response::SharedPtrの型を使用しましょう

2023-05-14 11:17 UTC, uhobeike commented on src/emcl2_node.cpp
> +  std::shared_ptr<std_srvs::srv::Empty::Request> req,
同じく

2023-05-14 11:17 UTC, uhobeike commented on src/emcl2_node.cpp
> +  std::shared_ptr<std_srvs::srv::Empty::Response> res)
同じく

2023-05-14 12:21 UTC, Kenzo-Fujisaki commented
@uhobeike 修正しました。再度レビューお願いします。

2023-05-15 05:48 UTC, uhobeike commented
@Kenzo-Fujisaki 実行できませんよ
> `ros2 run emcl2 emcl2_node ` `ros2 service call /global_localization std_srvs/srv/Empty {}\` を実行したところ
> 
> ```
> requester: making request: std_srvs.srv.Empty_Request()
> 
> response:
> std_srvs.srv.Empty_Response()
> ```

2023-05-15 05:57 UTC, uhobeike requested changes
修正お願いします。

2023-05-15 05:57 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +	rclcpp::Subscription<nav_msgs::msg::OccupancyGrid>::ConstSharedPtr map_sub_;
ここは、ConstSharedPtrである必要はありません。

2023-05-15 06:00 UTC, uhobeike commented
@Kenzo-Fujisaki 
マップを受け取るためのサービスは不要なので
それに関連するものの削除をお願いします。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/blob/59adc20bc1270cbd7088733263e70051a4a8f449/src/emcl2_node.cpp#L134-L135

2023-05-15 06:46 UTC, Kenzo-Fujisaki commented
@uhobeike 修正しましたので、再度レビューお願いします。
また、{}/の後にスペースが抜けていたので修正しました。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/18#issuecomment-1546873076

2023-05-15 06:56 UTC, uhobeike requested changes
ここで指摘した箇所が
消えてないですよ。
もうちょっと考えて修正してください。
https://github.com/CIT-Autonomous-Robot-Lab/emcl2_ros2/pull/18#issuecomment-1547235994

2023-05-15 08:20 UTC, Kenzo-Fujisaki commented
@uhobeike 修正しましたので、再度レビューお願いします。

2023-05-15 08:34 UTC, uhobeike approved these changes
大丈夫そうです。

2023-05-15 08:34 UTC, uhobeike commented
@Kenzo-Fujisaki マージお願いします。

2023-05-15 08:35 UTC, merged