Feature/create ros2 class 23 05 07 17 11
CIT-Autonomous-Robot-Lab/emcl2_ros2 pull request #7
Opened 2023-05-07 10:43 UTC by makotoyoshigoe

-  emcl2_node.*の移行前の部分をコメントアウト
- emcl2_node.*を修正して、ROS 2のクラスを作成
- CMakeLists.txtを修正して、emcl2_node.cppを使ってビルドするように変更

2023-05-07 10:44 UTC, makotoyoshigoe commented
@uhobeike レビューお願いします。

2023-05-07 13:50 UTC, makotoyoshigoe commented
@uhobeike 再度レビューお願いします。

2023-05-08 00:04 UTC, makotoyoshigoe commented
@uhobeike レビューお願いします

2023-05-08 01:35 UTC, uhobeike requested changes
修正お願いします。

2023-05-08 01:35 UTC, uhobeike commented on src/emcl2_node.cpp
> +    rclcpp::spin_some(node);
node.loop()が呼ばれてないです

2023-05-08 01:35 UTC, uhobeike commented on src/emcl2_node.cpp
> +EMcl2Node::EMcl2Node() : Node("mcl_node"), count_(0)
ここのcount_はどこにも使ってないですよね？

2023-05-08 01:35 UTC, uhobeike commented on include/emcl2/emcl2_node.h
> +	size_t count_;
ここのcount_も

2023-05-08 01:35 UTC, uhobeike commented on src/emcl2_node.cpp
> +		rclcpp::spin_some(node);
node.loop()が呼ばれてないです

2023-05-08 01:47 UTC, makotoyoshigoe commented
了解しました、ありがとうございます。

2023-05-08 02:40 UTC, makotoyoshigoe commented
@uhobeike 修正しました、確認お願いします。

2023-05-08 02:52 UTC, uhobeike approved these changes
良さそうです。

2023-05-08 02:53 UTC, uhobeike commented
@makotoyoshigoe こちらの修正したコードは実行してみましたか？（動作確認済み？）

2023-05-08 02:58 UTC, makotoyoshigoe commented
```ros2 run emcl2 emcl2_node```を打って実行しました。
その後```ros2 node list```を打ったところ、```/mcl_node```が表示されました。

2023-05-08 03:03 UTC, uhobeike requested changes
修正お願いします。

2023-05-08 03:03 UTC, uhobeike commented on src/emcl2_node.cpp
> +EMcl2Node::EMcl2Node() : Node("mcl_node")
ここをemcl2_nodeに修正しましょう
https://github.com/ryuichiueda/emcl2/blob/c9be751ca73ba025f58c0901c0f92b4bbdbf469e/src/emcl2_node.cpp#L318

2023-05-08 03:04 UTC, makotoyoshigoe commented on src/emcl2_node.cpp
> +EMcl2Node::EMcl2Node() : Node("mcl_node")
了解です。

2023-05-08 03:11 UTC, makotoyoshigoe commented on src/emcl2_node.cpp
> +EMcl2Node::EMcl2Node() : Node("mcl_node")
修正しました。

2023-05-08 03:11 UTC, uhobeike commented
動作確認はしました？

2023-05-08 03:13 UTC, uhobeike approved these changes
コードの方は大丈夫です。

2023-05-08 03:14 UTC, makotoyoshigoe commented
さっきと同じコマンドを打って確認しました。```ros2 node list```でノードの名前を確認したところ、```/emcl2_node```が表示されました。

2023-05-08 03:15 UTC, uhobeike commented
わかりました。
マージお願いします。

2023-05-08 03:15 UTC, makotoyoshigoe commented
了解しました。確認ありがとうございました。

2023-05-08 03:16 UTC, merged